# Generated by Django 3.2.20 on 2024-06-05 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыто?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 5, 12, 38, 3, 436428), verbose_name='Дата'),
        ),
    ]
